### ISSUE TITLE
 dataset ! HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by liyang-good** [TsingZ0/PFL-Non-IID#1]
python generate_mnist.py noniid realworld

**Comment by TsingZ0** [comment]
Sorry for the late reply. 
There has been a lot of trouble with the MNIST hosted on http://yann.lecun.com/exdb/mnist/

Thanks to the [solution](https://stackoverflow.com/questions/66646604/http-error-503-service-unavailable-when-trying-to-download-mnist-data) from StackOverflow, you can download the MNIST dataset manually by the following steps:

```
cd dataset/minst
mkdir rawdata
cd rawdata
wget www.di.ens.fr/~lelarge/MNIST.tar.gz
tar -zxvf MNIST.tar.gz
```

According to torch vision [issue 3549](https://github.com/pytorch/vision/issues/3549), this will be fixed in the next minor release, so I keep the codes unchanged.
