### ISSUE TITLE
FedAvg and FedBN result in the same 

### ISSUE THREAD

**Issue by nsh135** [TsingZ0/PFL-Non-IID#42]
please double check FedBN as it always give us same result as FedAvg

**Comment by TsingZ0** [comment]
The difference between FedAvg and FedBN only happens when you use a backbone with the Batch Normalization (BN) layer, such as ResNet-18 in this platform. FedBN localizes the BN layer on the client. If there is no BN layer, such as `cnn` in this platform, the results of FedBN are the same as FedAvg . You can also use a custom backbone with BN layers :-).
