### ISSUE TITLE
Ditto isn't be finished

### ISSUE THREAD

**Issue by hacker-jerry** [TsingZ0/PFL-Non-IID#6]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/57279550/162665857-ac45ead5-99a6-434e-b24a-2b4e1c7e788b.png">

the `set_parameters` method haven't been finished yet.

**Comment by hacker-jerry** [comment]
so that the program block

**Comment by hacker-jerry** [comment]
i can only run fedavg normally. Could you tell me what's wrong with me?
rtx 3090, torch 1.10, cuda 1.11.

**Comment by TsingZ0** [comment]
Thank you for pointing out this issue! I have fixed this bug in the current version. This bug comes up when merging several versions together. 

The details of the methods corresponding to the client object, such as `set_parameters()`, can be found in `clientbase.py` or the specific client class, such as `clientditto.py`, as all the specific client classes inherit from the `Client` class.

**Comment by hacker-jerry** [comment]
Thanks TsingZ0, I have tested the code and it works well!
By the way, I want to point out another little "bug" which may happen on some devices.
`label_binarize()` in every where it is called misses a parameter label "classes" after the first parameter.
The right way is `label_binarize(y,classes=[])`

**Comment by TsingZ0** [comment]
Thanks, hacker-jerry, I have updated the code in the new version.
